In [1]:
import pandas as pd

In [2]:
import mlxtend

In [3]:
diabetesresults=pd.read_csv('diabetes_binary_5050split_health_indicators_BRFSS2015_cleaned.csv')

In [4]:
diabetesresults.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,DiffWalk,Sex,Age,Education
0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,1,0,0
1,0,1,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,0
2,0,0,0,1,0,0,0,0,1,1,1,0,1,0,0,1,1,0
3,0,1,1,1,0,1,0,0,1,1,1,0,1,0,0,1,1,0
4,0,0,0,1,0,1,0,0,1,1,1,0,1,0,0,0,1,0

In [5]:
diabetesresults.describe()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,DiffWalk,Sex,Age,Education
count,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000
mean,0.500000,0.563458,0.525703,0.975259,0.444803,0.475273,0.062171,0.147810,0.703036,0.611795,0.788774,0.042721,0.954960,0.093914,0.252730,0.456997,0.848116,0.073120
std,0.500004,0.495960,0.499342,0.155336,0.496947,0.499392,0.241468,0.354914,0.456924,0.487345,0.408181,0.202228,0.207394,0.291712,0.434581,0.498151,0.358911,0.260335
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,0.500000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
diabetesresults

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,DiffWalk,Sex,Age,Education
0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,1,0,0
1,0,1,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,0
2,0,0,0,1,0,0,0,0,1,1,1,0,1,0,0,1,1,0
3,0,1,1,1,0,1,0,0,1,1,1,0,1,0,0,1,1,0
4,0,0,0,1,0,1,0,0,1,1,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1,0,1,1,1,0,0,0,0,0,1,0,1,0,0,0,1,0
70688,1,0,1,1,0,1,0,1,0,1,1,0,1,0,1,1,1,1
70689,1,1,1,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0
70690,1,1,1,1,0,0,0,0,0,0,0,0,1,0,1,0,1,1
70691,1,1,1,1,0,0,0,1,1,1,0,0,1,0,0,0,1,0

In [7]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [27]:
frequent_itemsets=apriori(diabetesresults,min_support=0.35, use_colnames=True)

C:\Users\sjjoh\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [28]:
frequent_itemsets

      support                                           itemsets
0    0.500000                                  (Diabetes_binary)
1    0.563458                                           (HighBP)
2    0.525703                                         (HighChol)
3    0.975259                                        (CholCheck)
4    0.444803                                              (BMI)
..        ...                                                ...
142  0.361484  (Veggies, Age, AnyHealthcare, HighChol, CholCh...
143  0.385334  (Veggies, AnyHealthcare, PhysActivity, CholChe...
144  0.367085  (Age, AnyHealthcare, PhysActivity, CholCheck, ...
145  0.458411  (Veggies, Age, AnyHealthcare, PhysActivity, Ch...
146  0.428974   (Veggies, Age, AnyHealthcare, CholCheck, Fruits)

[147 rows x 2 columns]

In [29]:
rules=association_rules(frequent_itemsets, metric='lift', min_threshold=1)

In [30]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(HighBP),(Diabetes_binary),0.563458,0.500000,0.376337,0.667905,1.335810,0.094608,1.505594
1,(Diabetes_binary),(HighBP),0.500000,0.563458,0.376337,0.752674,1.335810,0.094608,1.765042
2,(CholCheck),(Diabetes_binary),0.975259,0.500000,0.496591,0.509189,1.018378,0.008961,1.018722
3,(Diabetes_binary),(CholCheck),0.500000,0.975259,0.496591,0.993182,1.018378,0.008961,3.628631
4,(AnyHealthcare),(Diabetes_binary),0.954960,0.500000,0.479885,0.502518,1.005036,0.002405,1.005062
...,...,...,...,...,...,...,...,...,...
847,(Veggies),"(Fruits, CholCheck, Age, AnyHealthcare)",0.788774,0.497128,0.428974,0.543849,1.093980,0.036852,1.102423
848,(Age),"(Veggies, CholCheck, AnyHealthcare, Fruits)",0.848116,0.499151,0.428974,0.505796,1.013312,0.005636,1.013445
849,(AnyHealthcare),"(Veggies, CholCheck, Age, Fruits)",0.954960,0.441776,0.428974,0.449206,1.016819,0.007096,1.013490
850,(CholCheck),"(Veggies, Age, AnyHealthcare, Fruits)",0.975259,0.435594,0.428974,0.439856,1.009785,0.004157,1.007609
851,(Fruits),"(Veggies, CholCheck, Age, AnyHealthcare)",0.611795,0.632009,0.428974,0.701172,1.109434,0.042314,1.231448

In [31]:
ant_rules = rules[rules['consequents'] == {'Diabetes_binary'}]
consq_rules = rules[rules['antecedents'] == {'Diabetes_binary'}]

In [32]:
pd.concat([ant_rules,consq_rules])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(HighBP),(Diabetes_binary),0.563458,0.500000,0.376337,0.667905,1.335810,0.094608,1.505594
2,(CholCheck),(Diabetes_binary),0.975259,0.500000,0.496591,0.509189,1.018378,0.008961,1.018722
4,(AnyHealthcare),(Diabetes_binary),0.954960,0.500000,0.479885,0.502518,1.005036,0.002405,1.005062
6,(Age),(Diabetes_binary),0.848116,0.500000,0.468752,0.552698,1.105396,0.044694,1.117813
54,"(HighBP, CholCheck)",(Diabetes_binary),0.557475,0.500000,0.374314,0.671446,1.342891,0.095577,1.521818
60,"(HighBP, AnyHealthcare)",(Diabetes_binary),0.541759,0.500000,0.361922,0.668051,1.336101,0.091043,1.506253
66,"(HighBP, Age)",(Diabetes_binary),0.528928,0.500000,0.360437,0.681447,1.362895,0.095973,1.569600
74,"(CholCheck, AnyHealthcare)",(Diabetes_binary),0.934773,0.500000,0.477352,0.510661,1.021322,0.009966,1.021787
80,"(CholCheck, Age)",(Diabetes_binary),0.832074,0.500000,0.465781,0.559783,1.119566,0.049744,1.135804
88,"(Veggies, Age)",(Diabetes_binary),0.665125,0.500000,0.354312,0.532700,1.065399,0.021749,1.069975
92,"(AnyHealthcare, Age)",(Diabetes_binary),0.816613,0.500000,0.451565,0.552973,1.105945,0.043258,1.118500
322,"(HighBP, CholCheck, AnyHealthcare)",(Diabetes_binary),0.536949,0.500000,0.360324,0.671057,1.342115,0.091849,1.520022
336,"(HighBP, CholCheck, Age)",(Diabetes_binary),0.524062,0.500000,0.358570,0.684212,1.368424,0.096539,1.583340
356,"(Veggies, CholCheck, Age)",(Diabetes_binary),0.652719,0.500000,0.352204,0.539595,1.079190,0.025845,1.086001
366,"(CholCheck, Age, AnyHealthcare)",(Diabetes_binary),0.803316,0.500000,0.449273,0.559273,1.118546,0.047615,1.134489
1,(Diabetes_binary),(HighBP),0.500000,0.563458,0.376337,0.752674,1.335810,0.094608,1.765042
3,(Diabetes_binary),(CholCheck),0.500000,0.975259,0.496591,0.993182,1.018378,0.008961,3.628631
5,(Diabetes_binary),(AnyHealthcare),0.500000,0.954960,0.479885,0.959769,1.005036,0.002405,1.119550
7,(Diabetes_binary),(Age),0.500000,0.848116,0.468752,0.937504,1.105396,0.044694,2.430285
59,(Diabetes_binary),"(HighBP, CholCheck)",0.500000,0.557475,0.374314,0.748628,1.342891,0.095577,1.760439
65,(Diabetes_binary),"(HighBP, AnyHealthcare)",0.500000,0.541759,0.361922,0.723844,1.336101,0.091043,1.659359
71,(Diabetes_binary),"(HighBP, Age)",0.500000,0.528928,0.360437,0.720874,1.362895,0.095973,1.687665
79,(Diabetes_binary),"(CholCheck, AnyHealthcare)",0.500000,0.934773,0.477352,0.954705,1.021322,0.009966,1.440037
85,(Diabetes_binary),"(CholCheck, Age)",0.500000,0.832074,0.465781,0.931562,1.119566,0.049744,2.453700
91,(Diabetes_binary),"(Veggies, Age)",0.500000,0.665125,0.354312,0.708623,1.065399,0.021749,1.149286
97,(Diabetes_binary),"(AnyHealthcare, Age)",0.500000,0.816613,0.451565,0.903129,1.105945,0.043258,1.893107
335,(Diabetes_binary),"(HighBP, CholCheck, AnyHealthcare)",0.500000,0.536949,0.360324,0.720647,1.342115,0.091849,1.657586
349,(Diabetes_binary),"(HighBP, CholCheck, Age)",0.500000,0.524062,0.358570,0.717139,1.368424,0.096539,1.682587
365,(Diabetes_binary),"(Veggies, CholCheck, Age)",0.500000,0.652719,0.352204,0.704408,1.079190,0.025845,1.174866
379,(Diabetes_binary),"(CholCheck, Age, AnyHealthcare)",0.500000,0.803316,0.449273,0.898546,1.118546,0.047615,1.938650